server:
  port: 9087
  context-path: /search
  tomcat:
    max-threads: 200
    max-connections: 50
    min-spare-threads: 5
#整合mybatis
mybatis:
  config-location: classpath:config/sqlMapConfig.xml
  mapper-locations:
  - classpath:mapper/*Mapper.xml

spring:
  #elastic配置
  elasticsearch:
    jest:
      uris: http://192.168.70.129:9200
      read-timeout: 6000
      username: elastic
      password: elastic
  #数据库配置
  datasource:
      name: mysql_test
      type: com.alibaba.druid.pool.DruidDataSource
      #druid相关配置
      druid:
        publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIQcKm1lQtx3CqgAh3jr0nCHq8Rhm8UlOuH+ft6Qgg9GJ7OT39qHRQATWsPJs4aqAGjmpQAwGi67E+RbhRBTcLECAwEAAQ==
        #监控统计拦截的filters
        filters: config,stat,log4j #wall
        driver-class-name: com.mysql.jdbc.Driver
        #基本属性
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        #加密方式:java -cp druid-1.1.13.jar com.alibaba.druid.filter.config.ConfigTools your password
        password: OgRtWKt+Ws20nzDSncwwpBhooYwmUJZ1QNdCoURubMnyY/nrd21sJCLAy1XBpJTGqM4czdE7zMdOdV1EpC4w1Q==
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publicKey}
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        filter:
          config:
            enabled: true
  #thymeleaf配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    content-type: text/html
    prefix: classpath:/templates/