server:
  port: 8000
  context-path: /search
spring:
  application:
    name: v-search
  profiles:
    active: dev

#查看自动配置报告
debug: true

#配置日志
logging:
  config: classpath:logback-spring.xml
  level:
    cn.ixan.boot.mapper: debug

