spring:
  application:
    name: boot-test
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: true
      maximum-pool-size: 60
      minimum-idle: 10
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      maxLifetime: 1800000
      read-only: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true

logging:
  file: /home/log/boot-test.log
  level:
    root: INFO
    com.ixan.boot.mapper: DEBUG

version: 20201006